# Generated by Django 4.1.7 on 2023-03-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("webpage", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("email_is_public", models.BooleanField(default=True)),
                ("foto", models.FileField(upload_to="uploads/")),
                ("orcid", models.CharField(max_length=200)),
                ("linkedin", models.CharField(max_length=200)),
                ("unidad", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="universidad.universidad")),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(max_length=200, null=True)),
                ("nombre_en", models.CharField(max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, max_length=2000)),
                ("descripcion_es", models.TextField(blank=True, max_length=2000, null=True)),
                ("descripcion_en", models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dominio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(max_length=200, null=True)),
                ("nombre_en", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(max_length=200, null=True)),
                ("nombre_en", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subarea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(max_length=200, null=True)),
                ("nombre_en", models.CharField(max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, max_length=2000)),
                ("descripcion_es", models.TextField(blank=True, max_length=2000, null=True)),
                ("descripcion_en", models.TextField(blank=True, max_length=2000, null=True)),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="persona.area")),
            ],
        ),
        migrations.CreateModel(
            name="ParticipacionComision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_participacion", models.DateField()),
                ("is_interna", models.BooleanField(default=False)),
                ("comentario", models.TextField(max_length=2000)),
                ("is_comentario_public", models.BooleanField(default=False)),
                ("academico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico")),
                ("comision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="universidad.comision")),
            ],
            options={
                "verbose_name_plural": "participaciones de comisiones",
            },
        ),
        migrations.CreateModel(
            name="EstudioUniversitario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descripcion", models.TextField(max_length=2000)),
                ("is_maximo", models.BooleanField(default=False)),
                ("año", models.IntegerField()),
                ("academico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico")),
                ("grado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.grado")),
            ],
            options={
                "verbose_name_plural": "estudios universitarios",
            },
        ),
        migrations.CreateModel(
            name="DominioAcademico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("academico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico")),
                ("dominio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.dominio")),
            ],
            options={
                "verbose_name_plural": "dominios academicos",
            },
        ),
        migrations.CreateModel(
            name="AmbitoTrabajo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("academico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico")),
                ("subarea", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.subarea")),
            ],
            options={
                "verbose_name_plural": "ambitos de trabajo",
            },
        ),
    ]
