# Generated by Django 4.1.7 on 2023-03-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParticipacionComision",
        ),
    ]
