# Generated by Django 4.1.7 on 2023-03-30 23:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_delete_participacioncomision"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="apellido",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="nombres_externos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=3
            ),
        ),
        migrations.AlterField(
            model_name="academico",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="academico",
            name="foto",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="academico",
            name="webpage",
            field=models.URLField(blank=True),
        ),
    ]
