# Generated by Django 4.1.7 on 2023-03-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_academico_apellido_academico_nombres_externos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="academico",
            name="rol",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
