# Generated by Django 4.1.7 on 2023-03-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0010_unidad_is_manual_universidad_is_manual"),
        ("persona", "0004_academico_is_manual_academico_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="unidad",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="universidad.unidad"),
        ),
    ]
