# Generated by Django 4.1.7 on 2023-04-07 01:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0005_alter_academico_unidad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academico",
            old_name="rol",
            new_name="orcid_rol",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="orcid",
        ),
        migrations.AddField(
            model_name="academico",
            name="dblp_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="fuente",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
            ),
        ),
        migrations.AddField(
            model_name="academico",
            name="orcid_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="academico",
            name="nombres_externos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
            ),
        ),
    ]
