# Generated by Django 4.1.7 on 2023-04-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0006_rename_rol_academico_orcid_rol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="dblp_affiliation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="github",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="researcherid_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="scholar_google_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="twitter",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academico",
            name="wikidata_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="academico",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
