# Generated by Django 4.1.7 on 2023-04-18 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0007_academico_dblp_affiliation_academico_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="academico",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academico",
            name="dblp_last_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academico",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="academico",
            name="n_conference",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="academico",
            name="n_journal",
            field=models.IntegerField(default=0),
        ),
    ]
