# Generated by Django 4.1.7 on 2023-04-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0008_academico_activo_academico_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="dblp_last_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
