# Generated by Django 4.1.7 on 2023-04-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0009_alter_academico_dblp_last_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="apellido",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
