# Generated by Django 4.1.7 on 2023-04-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0010_unidad_is_manual_universidad_is_manual"),
        ("persona", "0010_alter_academico_apellido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="unidad",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="universidad.unidad"),
        ),
    ]
