# Generated by Django 4.1.7 on 2023-05-09 01:21

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0011_alter_academico_unidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="fuente",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
            ),
        ),
        migrations.AlterField(
            model_name="academico",
            name="nombres_externos",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
            ),
        ),
    ]
