# Generated by Django 4.1.7 on 2023-05-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0012_alter_academico_fuente_and_more"),
    ]

    operations = [migrations.RenameModel("Academico", "Investigador")]
