# Generated by Django 4.1.7 on 2023-05-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0013_alter_unidad_webpage_academic"),
        ("persona", "0013_auto_20230520_2258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigador",
            name="email_is_public",
        ),
        migrations.RemoveField(
            model_name="investigador",
            name="is_manual",
        ),
        migrations.RemoveField(
            model_name="investigador",
            name="unidad",
        ),
        migrations.CreateModel(
            name="Academico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(blank=True, max_length=200, null=True)),
                ("webpage", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_is_public", models.BooleanField(default=True)),
                ("foto", models.FileField(blank=True, upload_to="uploads/")),
                ("orcid_id", models.CharField(blank=True, max_length=200)),
                ("dblp_id", models.CharField(blank=True, max_length=200)),
                ("wikidata_id", models.CharField(blank=True, max_length=200)),
                ("researcherid_id", models.CharField(blank=True, max_length=200)),
                ("scholar_google_id", models.CharField(blank=True, max_length=200)),
                ("github", models.CharField(blank=True, max_length=200)),
                ("linkedin", models.CharField(blank=True, max_length=200)),
                ("twitter", models.CharField(blank=True, max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("investigador", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.investigador")),
                ("unidad", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="universidad.unidad")),
            ],
        ),
        migrations.AlterField(
            model_name="ambitotrabajo",
            name="academico",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico"),
        ),
        migrations.AlterField(
            model_name="dominioacademico",
            name="academico",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico"),
        ),
        migrations.AlterField(
            model_name="estudiouniversitario",
            name="academico",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico"),
        ),
    ]
