# Generated by Django 4.1.7 on 2023-05-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0014_remove_investigador_email_is_public_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigador",
            options={"verbose_name_plural": "investigadores"},
        ),
    ]
