# Generated by Django 4.1.7 on 2023-05-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0015_alter_investigador_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigador",
            name="dblp_id",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
