# Generated by Django 4.1.7 on 2023-05-22 07:55

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0016_alter_investigador_dblp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigadorOnDemand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(blank=True, max_length=200, null=True)),
                ("webpage", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("foto", models.FileField(blank=True, upload_to="uploads/")),
                ("activo", models.BooleanField(default=True)),
                ("n_journal", models.IntegerField(default=0)),
                ("n_conference", models.IntegerField(default=0)),
                (
                    "fuente",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
                    ),
                ),
                (
                    "nombres_externos",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
                    ),
                ),
                ("orcid_id", models.CharField(blank=True, max_length=200)),
                ("orcid_rol", models.CharField(blank=True, default="", max_length=200)),
                ("dblp_id", models.CharField(blank=True, max_length=200, unique=True)),
                ("dblp_affiliation", models.CharField(blank=True, default="", max_length=200)),
                ("dblp_last_publication_date", models.DateField(blank=True, null=True)),
                ("wikidata_id", models.CharField(blank=True, max_length=200)),
                ("researcherid_id", models.CharField(blank=True, max_length=200)),
                ("scholar_google_id", models.CharField(blank=True, max_length=200)),
                ("github", models.CharField(blank=True, max_length=200)),
                ("linkedin", models.CharField(blank=True, max_length=200)),
                ("twitter", models.CharField(blank=True, max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "investigadores on demand",
            },
        ),
        migrations.RemoveField(
            model_name="academico",
            name="investigador",
        ),
    ]
