# Generated by Django 4.1.7 on 2023-05-22 08:24

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0017_investigadorondemand_remove_academico_investigador"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigadorCandidato",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seleccionado", models.CharField(blank=True, max_length=200)),
                (
                    "candidatos",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=10
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="academico",
            name="investigador_candidato",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.investigadorcandidato"
            ),
        ),
    ]
