# Generated by Django 4.1.7 on 2023-05-23 01:15

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0018_investigadorcandidato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorcandidato",
            name="buscado",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="investigadorcandidato",
            name="candidatos",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=25
            ),
        ),
    ]
