# Generated by Django 4.1.7 on 2023-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0019_investigadorcandidato_buscado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorcandidato",
            name="seleccionado",
        ),
        migrations.AddField(
            model_name="academico",
            name="investigador_candidato_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investigadorcandidato",
            name="valid",
            field=models.BooleanField(default=False),
        ),
    ]
