# Generated by Django 4.1.7 on 2023-05-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0020_remove_investigadorcandidato_seleccionado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigadorcandidato",
            name="buscado",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
