# Generated by Django 4.1.7 on 2023-05-23 05:18

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0021_alter_investigadorcandidato_buscado"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="nombres_alternativos",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
            ),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="foto",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="github",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="orcid_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="researcherid_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="scholar_google_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="webpage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="wikidata_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
