# Generated by Django 4.1.7 on 2023-05-26 03:14

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0022_academico_nombres_alternativos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="coautor",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=20
            ),
        ),
    ]
