# Generated by Django 4.1.7 on 2023-05-26 05:47

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0023_investigadorondemand_coautor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigadorondemand",
            name="coautor",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=20
            ),
        ),
    ]
