# Generated by Django 4.1.7 on 2023-05-29 05:05

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0024_alter_investigadorondemand_coautor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigadorcandidato",
            name="candidatos",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=150
            ),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="coautor",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=100
            ),
        ),
    ]
