# Generated by Django 4.1.7 on 2023-06-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0026_add_trigramextension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subarea",
            name="area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.area"),
        ),
    ]
