# Generated by Django 4.1.7 on 2023-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0027_alter_subarea_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambitotrabajo",
            name="peso",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
