# Generated by Django 4.1.7 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0028_ambitotrabajo_peso"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="aminer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
