# Generated by Django 4.1.7 on 2023-06-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0029_investigadorondemand_aminer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbitoTrabajoInvestigador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peso", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("investigador", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.investigadorondemand")),
                ("subarea", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.subarea")),
            ],
            options={
                "verbose_name_plural": "ambitos de trabajo",
            },
        ),
    ]
