# Generated by Django 4.1.7 on 2023-06-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0030_ambitotrabajoinvestigador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="KeywordInvestigador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peso", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("investigador", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.investigadorondemand")),
                ("keyword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.keyword")),
            ],
            options={
                "verbose_name_plural": "ambitos de trabajo investigador",
            },
        ),
        migrations.CreateModel(
            name="Specificarea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, max_length=2000)),
                ("subarea", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.subarea")),
            ],
        ),
        migrations.RemoveField(
            model_name="ambitotrabajo",
            name="subarea",
        ),
        migrations.DeleteModel(
            name="AmbitoTrabajoInvestigador",
        ),
        migrations.AddField(
            model_name="ambitotrabajo",
            name="specificarea",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="persona.specificarea"),
        ),
    ]
