# Generated by Django 4.1.7 on 2023-06-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0031_keyword_keywordinvestigador_specificarea_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keywordinvestigador",
            options={"verbose_name_plural": "Keywords investigador"},
        ),
    ]
