# Generated by Django 4.1.7 on 2023-06-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0032_alter_keywordinvestigador_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambitotrabajo",
            name="specificarea",
        ),
        migrations.AddField(
            model_name="ambitotrabajo",
            name="subarea",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="persona.subarea"),
        ),
    ]
