# Generated by Django 4.1.7 on 2023-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0033_remove_ambitotrabajo_specificarea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="grado_maximo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Phd", "Doctor"),
                    ("Master", "Magíster"),
                    ("Bachelor", "Licenciado"),
                    ("Bachelor", "Bachiller"),
                    ("Technician", "Técnico Superior"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="EstudioUniversitario",
        ),
        migrations.DeleteModel(
            name="Grado",
        ),
    ]
