# Generated by Django 4.1.7 on 2023-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0034_academico_grado_maximo_delete_estudiouniversitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="grado_maximo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Phd", "Doctor"),
                    ("Master", "Magíster"),
                    ("Graduate", "Licenciado"),
                    ("Bachelor", "Bachiller"),
                    ("Technician", "Técnico Superior"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
