# Generated by Django 4.1.7 on 2023-06-21 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0037_alter_academico_grado_maximo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoautorInvestigador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peso", models.IntegerField()),
                (
                    "investigador_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="investigador_a", to="persona.investigadorondemand"
                    ),
                ),
                (
                    "investigador_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="investigador_b", to="persona.investigadorondemand"
                    ),
                ),
            ],
        ),
    ]
