# Generated by Django 4.1.7 on 2023-06-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0038_coautorinvestigador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="coautor",
        ),
    ]
