# Generated by Django 4.1.7 on 2023-07-04 04:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0039_remove_investigadorondemand_coautor"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="AcademicoInvitacion",
            fields=[
                ("code", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("expiration", models.DateTimeField()),
                ("is_confirmed", models.BooleanField(default=False)),
                ("academico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.academico")),
            ],
        ),
    ]
