# Generated by Django 4.1.7 on 2023-07-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0040_academico_user_academicoinvitacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambitotrabajo",
            name="subarea",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.subarea"),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="area",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="persona.area"),
        ),
        migrations.DeleteModel(
            name="Specificarea",
        ),
    ]
