# Generated by Django 4.1.7 on 2023-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0041_alter_ambitotrabajo_subarea_alter_subarea_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambitotrabajo",
            name="manual",
            field=models.BooleanField(default=False),
        ),
    ]
