# Generated by Django 4.1.7 on 2023-07-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0042_ambitotrabajo_manual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ambitotrabajo",
            old_name="activo",
            new_name="recomendado",
        ),
    ]
