# Generated by Django 4.1.7 on 2023-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0043_rename_activo_ambitotrabajo_recomendado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambitotrabajo",
            name="recomendado",
        ),
        migrations.AddField(
            model_name="ambitotrabajo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
