# Generated by Django 4.1.7 on 2025-06-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("persona", "0044_remove_ambitotrabajo_recomendado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="universidad",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="universidad.universidad"),
        ),
    ]
