# Generated by Django 4.1.7 on 2025-06-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("persona", "0045_academico_universidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="unidad",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="universidad.unidad"),
        ),
    ]
