# Generated by Django 4.1.7 on 2025-08-21 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0025_alter_unidad_unique_together"),
        ("persona", "0046_alter_academico_unidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academico",
            name="universidad",
        ),
        migrations.AlterField(
            model_name="academico",
            name="unidad",
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to="universidad.unidad"),
            preserve_default=False,
        ),
    ]
