# Generated by Django 4.1.7 on 2025-08-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0029_alter_unidad_unique_together"),
        ("persona", "0047_remove_academico_universidad_alter_academico_unidad"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="academico",
            unique_together={("nombre", "apellido", "unidad")},
        ),
    ]
