# Generated by Django 4.1.7 on 2025-09-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0048_alter_academico_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="is_aminer_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="is_dblp_fetched",
            field=models.BooleanField(default=False),
        ),
    ]
