# Generated by Django 4.1.7 on 2025-09-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0049_investigadorondemand_is_aminer_fetched_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="is_aminer_fetched",
            new_name="aminer_data_fetched",
        ),
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="is_dblp_fetched",
            new_name="dblp_data_fetched",
        ),
    ]
