# Generated by Django 4.1.7 on 2025-09-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0050_rename_is_aminer_fetched_investigadorondemand_aminer_data_fetched_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Investigador",
        ),
    ]
