# Generated by Django 4.1.7 on 2025-09-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0051_delete_investigador"),
    ]

    operations = [
        migrations.AddField(
            model_name="academico",
            name="investigador_ondemand",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.investigadorondemand"),
        ),
    ]
