# Generated by Django 4.1.7 on 2025-09-15 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0052_academico_investigador_ondemand"),
    ]

    operations = [
        migrations.AddField(
            model_name="coautorinvestigador",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
