# Generated by Django 4.1.7 on 2025-09-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0053_coautorinvestigador_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coautorinvestigador",
            name="created_date",
        ),
    ]
