# Generated by Django 4.1.7 on 2025-09-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0054_remove_coautorinvestigador_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academico",
            name="dblp_id",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="nombres_alternativos",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="orcid_id",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="researcherid_id",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="scholar_google_id",
        ),
        migrations.RemoveField(
            model_name="academico",
            name="wikidata_id",
        ),
    ]
