# Generated by Django 4.1.7 on 2025-09-24 16:36

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0055_remove_academico_dblp_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_data_fetched",
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_cited_by_counts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_display_name_alternative",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=10
            ),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_id_orcid",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_id_scopus",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_id_wikipedia",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_works_counts",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
