# Generated by Django 4.1.7 on 2025-09-24 16:56

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0056_remove_investigadorondemand_dblp_data_fetched_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_last_known_institutions",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=10
            ),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_topics",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=20
            ),
        ),
    ]
