# Generated by Django 4.1.7 on 2025-09-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0057_investigadorondemand_openalex_last_known_institutions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_last_known_institutions",
        ),
    ]
