# Generated by Django 4.1.7 on 2025-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0058_remove_investigadorondemand_openalex_last_known_institutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_last_known_institutions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
