# Generated by Django 4.1.7 on 2025-09-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0059_investigadorondemand_openalex_last_known_institutions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigadorondemand",
            name="dblp_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
