# Generated by Django 4.1.7 on 2025-09-25 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0060_alter_investigadorondemand_dblp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="investigador_ondemand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academico",
                to="persona.investigadorondemand",
            ),
        ),
    ]
