# Generated by Django 4.1.7 on 2025-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0062_alter_academico_investigador_ondemand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="aminer_data_fetched",
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="aminer_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
