# Generated by Django 4.1.7 on 2025-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0063_remove_investigadorondemand_aminer_data_fetched_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
