# Generated by Django 4.1.7 on 2025-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0064_investigadorondemand_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="academico",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
