# Generated by Django 4.1.7 on 2025-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0065_remove_investigadorondemand_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="aminer_last_fetched_date",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_last_fetched_date",
        ),
        migrations.AddField(
            model_name="academico",
            name="aminer_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="academico",
            name="dblp_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="academico",
            name="openalex_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
