# Generated by Django 4.1.7 on 2025-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0066_remove_investigadorondemand_aminer_last_fetched_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="aminer_last_fetched_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academico",
            name="dblp_last_fetched_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academico",
            name="openalex_last_fetched_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
