# Generated by Django 4.1.7 on 2025-10-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0067_alter_academico_aminer_last_fetched_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="investigador_candidato",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="persona.investigadorcandidato"),
        ),
        migrations.AlterField(
            model_name="academico",
            name="investigador_ondemand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academicos",
                to="persona.investigadorondemand",
            ),
        ),
    ]
