# Generated by Django 4.1.7 on 2025-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0068_alter_academico_investigador_candidato_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="fuente",
        ),
    ]
