# Generated by Django 4.1.7 on 2025-10-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0069_remove_investigadorondemand_fuente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="github",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="scholar_google_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="twitter",
        ),
    ]
