# Generated by Django 4.1.7 on 2025-10-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0070_remove_investigadorondemand_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="investigador_ondemand",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academico",
                to="persona.investigadorondemand",
            ),
        ),
    ]
