# Generated by Django 4.1.7 on 2025-10-12 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0071_alter_academico_investigador_ondemand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="investigador_ondemand",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academico",
                to="persona.investigadorondemand",
            ),
        ),
    ]
