# Generated by Django 4.1.7 on 2025-10-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0072_alter_academico_investigador_ondemand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="email",
            new_name="aminer_email",
        ),
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="webpage",
            new_name="aminer_webpage",
        ),
    ]
