# Generated by Django 4.1.7 on 2025-10-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0073_rename_email_investigadorondemand_aminer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="n_conference",
            new_name="dblp_n_conference",
        ),
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="n_journal",
            new_name="dblp_n_journal",
        ),
        migrations.RenameField(
            model_name="investigadorondemand",
            old_name="nombres_externos",
            new_name="dblp_nombres_externos",
        ),
    ]
