# Generated by Django 4.1.7 on 2025-10-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0074_rename_n_conference_investigadorondemand_dblp_n_conference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
