# Generated by Django 4.1.7 on 2025-10-14 22:43

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


def migrate_investigador_profiles(apps, schema_editor):
    InvestigadorOnDemand = apps.get_model("persona", "InvestigadorOnDemand")
    DblpProfile = apps.get_model("persona", "DblpProfile")
    AminerProfile = apps.get_model("persona", "AminerProfile")
    OpenAlexProfile = apps.get_model("persona", "OpenAlexProfile")

    for inv in InvestigadorOnDemand.objects.all():
        # Migrate DBLP fields
        dblp = DblpProfile.objects.create(
            dblp_n_journal=getattr(inv, "dblp_n_journal", 0),
            dblp_n_conference=getattr(inv, "dblp_n_conference", 0),
            dblp_id=getattr(inv, "dblp_id", None),
            dblp_affiliation=getattr(inv, "dblp_affiliation", ""),
            dblp_last_publication_date=getattr(inv, "dblp_last_publication_date", None),
            dblp_nombres_externos=getattr(inv, "dblp_nombres_externos", []),
            dblp_orcid_id=getattr(inv, "dblp_orcid_id", None),
        )

        # Migrate Aminer fields
        aminer = AminerProfile.objects.create(
            aminer_id=getattr(inv, "aminer_id", None),
            aminer_webpage=getattr(inv, "aminer_webpage", None),
            aminer_email=getattr(inv, "aminer_email", None),
        )

        # Migrate OpenAlex fields
        openalex = OpenAlexProfile.objects.create(
            openalex_id=getattr(inv, "openalex_id", None),
            openalex_id_orcid=getattr(inv, "openalex_id_orcid", None),
            openalex_id_scopus=getattr(inv, "openalex_id_scopus", None),
            openalex_id_wikipedia=getattr(inv, "openalex_id_wikipedia", None),
            openalex_display_name=getattr(inv, "openalex_display_name", None),
            openalex_display_name_alternative=getattr(inv, "openalex_display_name_alternative", []),
            openalex_works_counts=getattr(inv, "openalex_works_counts", None),
            openalex_cited_by_counts=getattr(inv, "openalex_cited_by_counts", None),
            openalex_last_known_institutions=getattr(inv, "openalex_last_known_institutions", []),
            openalex_topics=getattr(inv, "openalex_topics", []),
        )

        inv.dblp_profile_id = dblp.id
        inv.aminer_profile_id = aminer.id
        inv.openalex_profile_id = openalex.id
        inv.save()


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0075_alter_academico_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AminerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aminer_id", models.CharField(blank=True, max_length=200, null=True)),
                ("aminer_webpage", models.URLField(blank=True, null=True)),
                ("aminer_email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DblpProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dblp_n_journal", models.IntegerField(default=0)),
                ("dblp_n_conference", models.IntegerField(default=0)),
                ("dblp_id", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("dblp_affiliation", models.CharField(blank=True, default="", max_length=200)),
                ("dblp_last_publication_date", models.DateField(blank=True, null=True)),
                (
                    "dblp_nombres_externos",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=5
                    ),
                ),
                ("dblp_orcid_id", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpenAlexProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("openalex_id", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("openalex_id_orcid", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("openalex_id_scopus", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("openalex_id_wikipedia", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ("openalex_display_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "openalex_display_name_alternative",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=10
                    ),
                ),
                ("openalex_works_counts", models.IntegerField(blank=True, null=True)),
                ("openalex_cited_by_counts", models.IntegerField(blank=True, null=True)),
                ("openalex_last_known_institutions", models.JSONField(blank=True, default=list)),
                (
                    "openalex_topics",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=20
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="aminer_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.aminerprofile"),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="dblp_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.dblpprofile"),
        ),
        migrations.AddField(
            model_name="investigadorondemand",
            name="openalex_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.openalexprofile"),
        ),
        # migrations.RunPython(migrate_investigador_profiles),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="aminer_email",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="aminer_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="aminer_webpage",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_affiliation",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_last_publication_date",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_n_conference",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_n_journal",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="dblp_nombres_externos",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_cited_by_counts",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_display_name",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_display_name_alternative",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_id_orcid",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_id_scopus",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_id_wikipedia",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_last_known_institutions",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_topics",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="openalex_works_counts",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="orcid_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="orcid_rol",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="researcherid_id",
        ),
        migrations.RemoveField(
            model_name="investigadorondemand",
            name="wikidata_id",
        ),
    ]
