# Generated by Django 4.1.7 on 2025-10-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0076_aminerprofile_dblpprofile_openalexprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aminerprofile",
            name="aminer_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="aminer_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigador_ondemand",
                to="persona.aminerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="dblp_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigador_ondemand",
                to="persona.dblpprofile",
            ),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="openalex_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigador_ondemand",
                to="persona.openalexprofile",
            ),
        ),
    ]
