# Generated by Django 4.1.7 on 2025-10-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0077_alter_aminerprofile_aminer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigadorondemand",
            name="aminer_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.aminerprofile"),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="dblp_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.dblpprofile"),
        ),
        migrations.AlterField(
            model_name="investigadorondemand",
            name="openalex_profile",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.openalexprofile"),
        ),
    ]
