# Generated by Django 4.1.7 on 2025-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0079_alter_investigadorondemand_aminer_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigadorondemand",
            name="manual_orcid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
