# Generated by Django 4.1.7 on 2025-10-17 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0080_investigadorondemand_manual_orcid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="investigador_candidato",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="persona.investigadorcandidato"
            ),
        ),
    ]
