# Generated by Django 4.1.7 on 2025-10-28 11:09

from django.db import migrations, models


def map_grado_maximo_to_gradotipo(apps, schema_editor):
    """
    Map existing grado_maximo string values to GradoTipo choices
    """
    Academico = apps.get_model("persona", "Academico")

    # Mapping from old string values to new GradoTipo values
    grado_mapping = {
        # Old string values (from commented GRADOS) -> New GradoTipo values
        "Phd": "PHD",  # Doctorado
        "Master": "MSC",  # Maestría
        "Graduate": "LIC",  # Licenciado/Ingeniero -> Licenciatura
        "Bachelor": "BACH",  # Bachiller
        "Technician": "TECH",  # Técnico Superior
        # Handle possible variations (case insensitive)
        "phd": "PHD",
        "PhD": "PHD",
        "master": "MSC",
        "Master": "MSC",
        "graduate": "LIC",
        "Graduate": "LIC",
        "bachelor": "BACH",
        "Bachelor": "BACH",
        "technician": "TECH",
        "Technician": "TECH",
        # Handle Spanish variations if any exist
        "Doctorado": "PHD",
        "Maestría": "MSC",
        "Maestria": "MSC",
        "Magíster": "MSC",
        "Magister": "MSC",
        "Licenciado": "LIC",
        "Licenciatura": "LIC",
        "Ingeniero": "LIC",
        "Bachiller": "BACH",
        "Técnico Superior": "TECH",
        "Tecnico Superior": "TECH",
    }

    # Get all academics with grado_maximo values
    academicos_to_update = []

    for academico in Academico.objects.exclude(grado_maximo__isnull=True).exclude(grado_maximo=""):
        old_value = academico.grado_maximo.strip()
        new_value = grado_mapping.get(old_value)

        if new_value:
            academico.grado_maximo = new_value
            academicos_to_update.append(academico)
            print(f"Mapping: {old_value} -> {new_value} for academico {academico.id}")
        else:
            # Log unmapped values for manual review
            print(f"WARNING: No mapping found for grado_maximo='{old_value}' (academico {academico.id})")
            # Set to UNKNOWN for unmapped values
            academico.grado_maximo = "UNK"
            academicos_to_update.append(academico)

    # Bulk update for efficiency
    if academicos_to_update:
        Academico.objects.bulk_update(academicos_to_update, ["grado_maximo"], batch_size=100)
        print(f"Updated {len(academicos_to_update)} academicos")


def reverse_map_grado_maximo(apps, schema_editor):
    """
    Reverse mapping for rollback (optional)
    """
    Academico = apps.get_model("persona", "Academico")

    # Reverse mapping from new GradoTipo values to old string values
    reverse_mapping = {
        "PHD": "Phd",
        "MSC": "Master",
        "LIC": "Graduate",
        "BACH": "Bachelor",
        "TECH": "Technician",
        "UNK": None,  # Set to null for unknown
    }

    academicos_to_update = []

    for academico in Academico.objects.exclude(grado_maximo__isnull=True):
        old_value = academico.grado_maximo
        new_value = reverse_mapping.get(old_value)

        if new_value is not None:
            academico.grado_maximo = new_value
            academicos_to_update.append(academico)
        elif old_value == "UNK":
            academico.grado_maximo = None
            academicos_to_update.append(academico)

    if academicos_to_update:
        Academico.objects.bulk_update(academicos_to_update, ["grado_maximo"], batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0081_alter_academico_investigador_candidato"),
    ]

    operations = [
        migrations.RunPython(map_grado_maximo_to_gradotipo, reverse_map_grado_maximo),
        migrations.AlterField(
            model_name="academico",
            name="grado_maximo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACH", "Bachiller"),
                    ("TECH", "Técnico Superior"),
                    ("LIC", "Licenciatura"),
                    ("MSC", "Maestria"),
                    ("PHD", "Doctorado"),
                    ("UNK", "Desconocido"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
