# Generated by Django 4.1.7 on 2025-11-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0082_alter_academico_grado_maximo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dblpprofile",
            name="dblp_coauthors",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
