# Generated by Django 4.1.7 on 2025-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0083_dblpprofile_dblp_coauthors"),
    ]

    operations = [
        migrations.AddField(
            model_name="aminerprofile",
            name="aminer_interests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
