# Generated by Django 4.1.7 on 2025-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0084_aminerprofile_aminer_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="subarea",
            field=models.ManyToManyField(blank=True, to="persona.subarea"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
