# Generated by Django 4.1.7 on 2025-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0085_keyword_subarea_alter_keyword_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre_en",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre_es",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="nombre_en",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="nombre_es",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
