# Generated by Django 4.1.7 on 2025-11-04 21:33

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0086_alter_area_nombre_alter_area_nombre_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openalexprofile",
            name="openalex_topics",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=20
            ),
        ),
    ]
