# Generated by Django 4.1.7 on 2025-11-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0088_alter_openalexprofile_openalex_topics"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subarea",
            unique_together={("area", "nombre")},
        ),
    ]
