# Generated by Django 4.1.7 on 2025-11-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0089_alter_subarea_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subarea",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="nombre_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="subarea",
            name="nombre_es",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
