# Generated by Django 4.1.7 on 2025-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0090_alter_subarea_nombre_alter_subarea_nombre_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academico",
            name="grado_maximo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECH", "Técnico Superior"),
                    ("LIC", "Licenciatura"),
                    ("MSC", "Magister"),
                    ("PHD", "Doctorado"),
                    ("UNK", "Desconocido"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
