# Generated by Django 4.1.7 on 2025-11-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0091_alter_academico_grado_maximo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="subarea",
        ),
    ]
