# Generated by Django 4.1.7 on 2023-06-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
