FROM python:3.12.7-bookworm AS base

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /static /logs /media /backup

COPY app/ .

RUN pip install -r _requirements/base.txt
RUN  echo "Base requirements installed"
RUN pip install -r _requirements/production.txt
RUN  echo "Production requirements installed"
RUN pip install -r _requirements/develop.txt
RUN echo "develop requirements installed"
RUN echo "Production setup complete"
