# Generated by Django 4.1.7 on 2023-03-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoComision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(max_length=2000)),
            ],
            options={
                "verbose_name_plural": "Tipos de comision",
            },
        ),
        migrations.CreateModel(
            name="Universidad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=10)),
                ("webpage", models.URLField()),
                ("pais", models.CharField(max_length=200)),
                ("foto_escudo", models.FileField(blank=True, upload_to="uploads/")),
                ("foto_banner", models.FileField(blank=True, upload_to="uploads/")),
            ],
            options={
                "verbose_name_plural": "universidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=10)),
                ("webpage", models.URLField()),
                ("foto", models.FileField(blank=True, upload_to="uploads/")),
                ("universidad", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="universidad.universidad")),
            ],
            options={
                "verbose_name_plural": "unidades",
            },
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(max_length=2000)),
                ("is_public", models.BooleanField(default=False)),
                ("tipo_comision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="universidad.tipocomision")),
                ("universidad", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="universidad.universidad")),
            ],
            options={
                "verbose_name_plural": "comisiones",
            },
        ),
    ]
