# Generated by Django 4.1.7 on 2023-03-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_delete_participacioncomision"),
        ("universidad", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comision",
        ),
        migrations.DeleteModel(
            name="TipoComision",
        ),
    ]
