# Generated by Django 4.1.7 on 2023-03-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0002_delete_comision_delete_tipocomision"),
    ]

    operations = [
        migrations.AddField(
            model_name="universidad",
            name="orcid",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
