# Generated by Django 4.1.7 on 2023-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0003_universidad_orcid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universidad",
            name="orcid",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
