# Generated by Django 4.1.7 on 2023-03-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0004_alter_universidad_orcid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="universidad",
            old_name="orcid",
            new_name="ringgold",
        ),
    ]
