# Generated by Django 4.1.7 on 2023-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0005_rename_orcid_universidad_ringgold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="universidad",
            name="ringgold",
        ),
        migrations.AddField(
            model_name="universidad",
            name="id_crossref",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="id_isni",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="id_ringgold",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="id_ror",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="id_wikidata",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
