# Generated by Django 4.1.7 on 2023-03-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0006_remove_universidad_ringgold_universidad_id_crossref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="universidad",
            name="is_cruch",
            field=models.BooleanField(default=False),
        ),
    ]
