# Generated by Django 4.1.7 on 2023-03-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0007_universidad_is_cruch"),
    ]

    operations = [
        migrations.AddField(
            model_name="universidad",
            name="casa_central",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
