# Generated by Django 4.1.7 on 2023-03-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0008_universidad_casa_central"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="webpage",
            field=models.URLField(blank=True),
        ),
    ]
