# Generated by Django 4.1.7 on 2023-03-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0009_alter_unidad_webpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidad",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="universidad",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
