# Generated by Django 4.1.7 on 2023-05-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0010_unidad_is_manual_universidad_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidad",
            name="webpage_academic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
