# Generated by Django 4.1.7 on 2023-05-29 05:05

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0014_unidad_created_date_unidad_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="webpage_academic",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.URLField(blank=True, null=True), blank=True, default=list, size=10
            ),
        ),
    ]
