# Generated by Django 4.1.7 on 2023-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0015_alter_unidad_webpage_academic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidad",
            name="foto",
        ),
        migrations.AddField(
            model_name="unidad",
            name="foto_escudo",
            field=models.FileField(blank=True, upload_to="uploads/universidades"),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="foto_banner",
            field=models.FileField(blank=True, upload_to="uploads/universidades/"),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="foto_escudo",
            field=models.FileField(blank=True, upload_to="uploads/universidades/"),
        ),
    ]
