# Generated by Django 4.1.7 on 2023-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0016_remove_unidad_foto_unidad_foto_escudo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="foto_escudo",
            field=models.FileField(blank=True, upload_to="universidades/"),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="foto_banner",
            field=models.FileField(blank=True, upload_to="universidades/"),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="foto_escudo",
            field=models.FileField(blank=True, upload_to="universidades/"),
        ),
    ]
