# Generated by Django 4.1.7 on 2023-06-09 04:37

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0017_alter_unidad_foto_escudo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidad",
            name="webpage_academic",
        ),
        migrations.AddField(
            model_name="universidad",
            name="webpage_academic",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.URLField(blank=True, null=True), blank=True, default=list, size=10
            ),
        ),
    ]
