# Generated by Django 4.1.7 on 2023-06-13 04:56

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0018_remove_unidad_webpage_academic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universidad",
            name="pais",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
