# Generated by Django 4.1.7 on 2023-06-25 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("universidad", "0019_alter_universidad_pais"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretarioInstitucionInvitacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30)),
                ("expiration", models.DateTimeField()),
                ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="universidad.universidad")),
            ],
        ),
        migrations.CreateModel(
            name="SecretarioInstitucion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="universidad.universidad")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
