# Generated by Django 4.1.7 on 2023-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0020_secretarioinstitucioninvitacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretarioinstitucioninvitacion",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
