# Generated by Django 4.1.7 on 2023-06-26 02:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0021_secretarioinstitucioninvitacion_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretarioinstitucioninvitacion",
            name="code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
