# Generated by Django 4.1.7 on 2023-06-26 02:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0022_alter_secretarioinstitucioninvitacion_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretarioinstitucioninvitacion",
            name="id",
        ),
        migrations.AlterField(
            model_name="secretarioinstitucioninvitacion",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
