# Generated by Django 4.1.7 on 2025-05-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0023_remove_secretarioinstitucioninvitacion_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="universidad",
            unique_together={("nombre", "pais")},
        ),
    ]
