# Generated by Django 4.1.7 on 2025-08-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unidad",
            unique_together={("universidad", "nombre")},
        ),
    ]
