# Generated by Django 4.1.7 on 2025-08-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0025_alter_unidad_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
