# Generated by Django 4.1.7 on 2025-08-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0026_alter_unidad_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="sigla",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
