# Generated by Django 4.1.7 on 2025-08-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0027_alter_unidad_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="foto_escudo",
            field=models.FileField(blank=True, null=True, upload_to="universidades/"),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="webpage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
