# Generated by Django 4.1.7 on 2025-08-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0028_alter_unidad_foto_escudo_alter_unidad_webpage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unidad",
            unique_together={("universidad", "nombre"), ("universidad", "sigla")},
        ),
    ]
