# Generated by Django 4.1.7 on 2025-09-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0029_alter_unidad_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="universidad",
            unique_together={("sigla", "pais"), ("nombre", "pais")},
        ),
    ]
