# Generated by Django 4.1.7 on 2025-09-17 15:43

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0031_alter_universidad_sigla"),
    ]

    operations = [
        migrations.AddField(
            model_name="universidad",
            name="id_openalex",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_acronims",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, default=None, max_length=50, null=True), blank=True, default=list, size=10
            ),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_alternative_names",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, default=None, max_length=200, null=True), blank=True, default=list, size=50
            ),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_city_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_city_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_en_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_es_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_home_page_url",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_id_grid",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_id_mag",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_id_ror",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_id_wikidata",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_id_wikipedia",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_is_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_region_latitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_region_longitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_thumbnail_url",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="universidad",
            name="openalex_type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
