# Generated by Django 4.1.7 on 2025-09-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0032_universidad_id_openalex_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="universidad",
            old_name="id_openalex",
            new_name="openalex_id",
        ),
    ]
