# Generated by Django 4.1.7 on 2025-09-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0033_rename_id_openalex_universidad_openalex_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="universidad",
            name="openalex_display_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
