# Generated by Django 4.1.7 on 2025-09-22 03:17

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0035_alter_universidad_openalex_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAlexInsitution",
            fields=[
                ("openalex_id", models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ("openalex_display_name", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("openalex_is_fetched", models.BooleanField(default=False)),
                ("openalex_home_page_url", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("openalex_thumbnail_url", models.CharField(blank=True, default=None, max_length=200, null=True)),
                (
                    "openalex_acronims",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, default=None, max_length=50, null=True), blank=True, default=list, size=10
                    ),
                ),
                ("openalex_type", models.CharField(blank=True, default=None, max_length=50, null=True)),
                (
                    "openalex_alternative_names",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(blank=True, default=None, max_length=200, null=True), blank=True, default=list, size=50
                    ),
                ),
                ("openalex_en_name", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("openalex_es_name", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("openalex_id_ror", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("openalex_id_mag", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("openalex_id_grid", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("openalex_id_wikipedia", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("openalex_id_wikidata", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("openalex_city_name", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("openalex_city_id", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("openalex_region_latitude", models.FloatField(blank=True, default=None, null=True)),
                ("openalex_region_longitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "universidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="openalex_institution", to="universidad.universidad"
                    ),
                ),
            ],
        ),
    ]
