# Generated by Django 4.1.7 on 2025-09-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0036_openalexinsitution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_acronims",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_alternative_names",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_city_id",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_city_name",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_display_name",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_en_name",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_es_name",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_home_page_url",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id_grid",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id_mag",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id_ror",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id_wikidata",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_id_wikipedia",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_is_fetched",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_region_latitude",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_region_longitude",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="universidad",
            name="openalex_type",
        ),
    ]
