# Generated by Django 4.1.7 on 2025-09-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0037_remove_universidad_openalex_acronims_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openalexinsitution",
            name="openalex_is_fetched",
        ),
        migrations.AddField(
            model_name="openalexinsitution",
            name="openalex_last_fetched_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
