# Generated by Django 4.1.7 on 2025-09-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0038_remove_openalexinsitution_openalex_is_fetched_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openalexinsitution",
            name="openalex_id",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="openalexinsitution",
            name="id",
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name="ID"),
            preserve_default=False,
        ),
    ]
