# Generated by Django 4.1.7 on 2025-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0039_openalexinsitution_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universidad",
            name="sigla",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
