# Generated by Django 4.1.7 on 2025-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0040_alter_universidad_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openalexinsitution",
            name="openalex_thumbnail_url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
