# Generated by Django 4.1.7 on 2025-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0041_alter_openalexinsitution_openalex_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openalexinsitution",
            name="openalex_home_page_url",
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="sigla",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
