# Generated by Django 4.1.7 on 2025-09-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0042_alter_openalexinsitution_openalex_home_page_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="universidad",
            unique_together={("nombre", "pais")},
        ),
    ]
