# Generated by Django 4.1.7 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0043_alter_universidad_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universidad",
            name="id_crossref",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="id_isni",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="id_ringgold",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="id_ror",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="universidad",
            name="id_wikidata",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
