# Generated by Django 4.1.7 on 2025-09-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0044_alter_universidad_id_crossref_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="universidad",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="universidad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)), fields=("nombre", "pais"), name="unique_nombre_pais_not_deleted"
            ),
        ),
    ]
