# Generated by Django 4.1.7 on 2025-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0045_alter_universidad_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openalexinsitution",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
