# Generated by Django 4.1.7 on 2025-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0046_openalexinsitution_is_deleted"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="openalexinsitution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)), fields=("openalex_id",), name="unique_openalex_id_not_deleted"
            ),
        ),
    ]
