# Generated by Django 4.1.7 on 2025-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0047_openalexinsitution_unique_openalex_id_not_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openalexinsitution",
            name="openalex_id",
            field=models.CharField(max_length=30),
        ),
    ]
