# Generated by Django 4.1.7 on 2025-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0048_alter_openalexinsitution_openalex_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidad",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
