# Generated by Django 4.1.7 on 2025-09-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0049_unidad_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="universidad",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="unidades_set", to="universidad.universidad"),
        ),
    ]
