# Generated by Django 4.1.7 on 2025-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0050_alter_unidad_universidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universidad",
            name="webpage",
            field=models.URLField(null=True),
        ),
    ]
