# Generated by Django 4.1.7 on 2025-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0051_alter_universidad_webpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidad",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
