services:
  django:
    networks:
      - nginx-proxy
    container_name: acad_micros
    hostname: acad_micros.apps.dcc.uchile.cl
    build: .
    command: gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm --bind :8000 wsgi
    volumes:
        - .:/usr/src/app/
        - /home/instalar/static/acad_micros/:/static/:rw
        - /home/instalar/media/acad_micros/:/media/:rw
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    expose:
      - 8000
    env_file:
      - ./.env.dev
    environment:
      - SCRIPT_NAME=/docencia/acad_micros/
      - DJANGO_SETTINGS_MODULE=memoria.settings
    restart: always

networks:
    nginx-proxy:
      external: true
      name: nginx-proxy
