# Generated by Django 4.1.7 on 2025-10-01 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidAcademicoEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unidad", models.CharField(blank=True, max_length=200)),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(blank=True, max_length=200, null=True)),
                ("webpage", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("grado_maximo", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
