# Generated by Django 4.1.7 on 2025-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invalidacademicoentry",
            name="universidad",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
