# Generated by Django 4.1.7 on 2025-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0002_invalidacademicoentry_universidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invalidacademicoentry",
            name="unidad",
        ),
    ]
