# Generated by Django 4.1.7 on 2025-10-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("revision", "0003_remove_invalidacademicoentry_unidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidGradoEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(blank=True, max_length=200, null=True)),
                ("web_site", models.URLField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                ("universidad", models.CharField(blank=True, max_length=200, null=True)),
                ("unidad", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_creacion", models.CharField(blank=True, max_length=50, null=True)),
                ("activo", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
