# Generated by Django 4.1.7 on 2025-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0004_invalidgradoentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidgradoentry",
            name="activo",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
