# Generated by Django 4.1.7 on 2025-10-01 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("revision", "0005_alter_invalidgradoentry_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorruptedAcademicoEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(blank=True, max_length=200, null=True)),
                ("universidad", models.CharField(blank=True, max_length=200)),
                ("webpage", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("grado_maximo", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "invalid_type",
                    models.CharField(
                        choices=[("invalid_university", "Corrupted University")], help_text="Type of invalid entry", max_length=50
                    ),
                ),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CorruptedGradoEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_es", models.CharField(blank=True, max_length=200, null=True)),
                ("web_site", models.URLField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                ("universidad", models.CharField(blank=True, max_length=200, null=True)),
                ("unidad", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_creacion", models.CharField(blank=True, max_length=50, null=True)),
                ("activo", models.BooleanField(default=False, null=True)),
                (
                    "invalid_type",
                    models.CharField(
                        choices=[("invalid_university", "Corrupted University")], help_text="Type of invalid entry", max_length=50
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name="invalidgradoentry",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="InvalidAcademicoEntry",
        ),
        migrations.DeleteModel(
            name="InvalidGradoEntry",
        ),
    ]
