# Generated by Django 4.1.7 on 2025-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0006_corruptedacademicoentry_corruptedgradoentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corruptedacademicoentry",
            name="pais_universidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="corruptedgradoentry",
            name="pais_universidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
