# Generated by Django 4.1.7 on 2025-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revision", "0007_corruptedacademicoentry_pais_universidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corruptedacademicoentry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="corruptedacademicoentry",
            name="webpage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
