# Generated by Django 4.1.7 on 2025-05-12 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universidad", "0023_remove_secretarioinstitucioninvitacion_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(choices=[("LIC", "Licenciatura"), ("MSC", "Maestria"), ("DOC", "Doctorado")], max_length=3)),
                ("anio_creacion", models.IntegerField(blank=True, null=True)),
                ("web_site", models.URLField(max_length=500, null=True)),
                ("activo", models.BooleanField(null=True)),
                ("universidad", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="universidad.universidad")),
            ],
        ),
    ]
