# Generated by Django 4.1.7 on 2025-05-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grado",
            name="anio_creacion",
        ),
        migrations.AddField(
            model_name="grado",
            name="fecha_creacion",
            field=models.DateField(null=True),
        ),
    ]
