# Generated by Django 4.1.7 on 2025-05-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0023_remove_secretarioinstitucioninvitacion_id_and_more"),
        ("grados", "0002_remove_grado_anio_creacion_grado_fecha_creacion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Grado",
            new_name="GradoInstancia",
        ),
    ]
