# Generated by Django 4.1.7 on 2025-05-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0003_rename_grado_gradoinstancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="tipo",
            field=models.CharField(choices=[("LIC", "Licenciatura"), ("MSC", "Maestria"), ("PHD", "Doctorado")], max_length=3),
        ),
    ]
