# Generated by Django 4.1.7 on 2025-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0005_alter_gradoinstancia_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="nombre",
            field=models.CharField(max_length=300),
        ),
    ]
