# Generated by Django 4.1.7 on 2025-05-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("grados", "0006_alter_gradoinstancia_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradoinstancia",
            name="unidad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universidad.unidad",
            ),
        ),
        migrations.AlterField(
            model_name="gradoinstancia",
            name="universidad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="universidad.universidad",
            ),
        ),
    ]
