# Generated by Django 4.1.7 on 2025-05-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("grados", "0007_gradoinstancia_unidad_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gradoinstancia",
            unique_together={("nombre", "tipo", "universidad")},
        ),
    ]
