# Generated by Django 4.1.7 on 2025-05-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("grados", "0008_alter_gradoinstancia_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gradoinstancia",
            unique_together={
                ("nombre", "tipo", "unidad"),
                ("nombre", "tipo", "universidad"),
            },
        ),
    ]
