# Generated by Django 4.1.7 on 2025-08-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0024_alter_universidad_unique_together"),
        ("grados", "0009_alter_gradoinstancia_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="universidad",
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to="universidad.universidad"),
            preserve_default=False,
        ),
    ]
