# Generated by Django 4.1.7 on 2025-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0010_alter_gradoinstancia_universidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="tipo",
            field=models.CharField(choices=[("LIC", "Licenciatura"), ("MSC", "Maestria"), ("PHD", "Doctorado")], max_length=30),
        ),
    ]
