# Generated by Django 4.1.7 on 2025-08-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universidad", "0025_alter_unidad_unique_together"),
        ("grados", "0011_alter_gradoinstancia_tipo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gradoinstancia",
            unique_together={("nombre", "tipo", "unidad")},
        ),
        migrations.RemoveField(
            model_name="gradoinstancia",
            name="universidad",
        ),
    ]
