# Generated by Django 4.1.7 on 2025-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0012_alter_gradoinstancia_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradoinstancia",
            name="nombre_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="gradoinstancia",
            name="nombre_es",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
