# Generated by Django 4.1.7 on 2025-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0013_gradoinstancia_nombre_en_gradoinstancia_nombre_es"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="tipo",
            field=models.CharField(
                choices=[("LIC", "Licenciatura"), ("MSC", "Maestria"), ("PHD", "Doctorado"), ("UNK", "Desconocido")], max_length=30
            ),
        ),
    ]
