# Generated by Django 4.1.7 on 2025-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0014_alter_gradoinstancia_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradoinstancia",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
