# Generated by Django 4.1.7 on 2025-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0015_gradoinstancia_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradoinstancia",
            name="validation_state",
            field=models.CharField(
                choices=[
                    ("VALID", "Válido"),
                    ("INVALID", "Inválido"),
                    ("PENDING", "Pendiente"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
