# Generated by Django 4.1.7 on 2025-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0016_gradoinstancia_validation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="validation_state",
            field=models.CharField(
                choices=[("VALID", "Válido"), ("INVALID_URL", "Inválido"), ("PENDING", "Pendiente")], default="PENDING", max_length=20
            ),
        ),
    ]
