# Generated by Django 4.1.7 on 2025-10-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0017_alter_gradoinstancia_validation_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gradoinstancia",
            old_name="validation_state",
            new_name="verification_state",
        ),
    ]
