# Generated by Django 4.1.7 on 2025-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grados", "0019_alter_gradoinstancia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradoinstancia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TECH", "Técnico Superior"),
                    ("LIC", "Licenciatura"),
                    ("MSC", "Magister"),
                    ("PHD", "Doctorado"),
                    ("UNK", "Desconocido"),
                ],
                max_length=30,
            ),
        ),
    ]
