services:
    django:
        networks:
            - nginx-proxy
        container_name: acad_micros
        hostname: acad_micros.apps.dcc.uchile.cl
        build: 
            context: ../
            dockerfile: .docker/app/Dockerfile
            target: production
            args:
                UID: 1001
                GID: 100
        command: gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm --env SCRIPT_NAME=/docencia/acad_micros/ --bind :8000 core.wsgi
        volumes:
            - /home/instalar/static/acad_micros/:/static/:rw
            - /home/instalar/media/acad_micros:/media/:rw
            - /home/instalar/logs/acad_micros:/logs:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        expose:
            - 8000
        env_file:
            - app/.env
        restart: always

networks:
    nginx-proxy:
      external: true
      name: nginx-proxy
